name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Set up protobuf
      run: sudo apt update -q && sudo apt install -y protobuf-compiler

    - name: Build
      run: make

   #  TODO: test
   #  - name: Test
   #    run: go test -v ./...
