name: Go

on:
  push:
    branches: [ master ]
  tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: '${{ secrets.QUAYIO_USERNAME }}'
          password: '${{ secrets.QUAYIO_PASSWORD }}'
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push -t quay.io/wish/eventmaster:${GITHUB_REF##*/} .
